server:
  port: 8282
application:
  kafka:
    orderTopicRequest: "orderTopicRequest"
    orderTopicResponse: "orderTopicResponse"
spring:
  datasource:
    url: jdbc:postgresql://localhost:5446/orderDB
    username: order
    password: pass
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
      value-deserializer: com.example.orderService.kafka.JsonDeserializer
      group-id: 'order-group-id'
    producer:
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: com.example.orderService.kafka.JsonSerializer
  boot:
    admin:
      client:
        url: http://localhost:8282/admin
      context-path: /admin
  jpa:
    show-sql: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
